### ISSUE TITLE
Feature Request: Choose arbitrary problem repo

### ISSUE THREAD

**Issue by ouuan** [pcovellite/frontend#1]
The feature I want: Users can choose the problem repo, get problems from other repos and submit.

I think the biggest advantage of a Git-based OJ is that anyone is free to modify the problems, so it will be much better if repos from anyone are supported.

**Comment by ouuan** [comment]
There could be a centralized repo list that accepts PRs to add more repos.

**Comment by ouuan** [comment]
It would be better if there's a way to identify the same problem in different repos. That might need a centralized list.

**Comment by ouuan** [comment]
If the centralized list is read from an issue instead of PR, then anyone is still free to modify it.

**Comment by diauweb** [comment]
I myself originally designed the entire project to be more easily forked into several decentralized distributions, as everyone can fork these repositories into a team or whatever to create their own CovOJ. But it will be great to break the walls between different problem repos.

**Comment by diauweb** [comment]
https://github.com/EtherOJ/EtherOJ/commit/d2da9d9303bea28e5978e11554f47d1d9c4ac266
https://github.com/EtherOJ/EtherJudger/commit/68ed097704a2faf55beea5ac2aabe0be22a6c448
